services:
  spark-master:
    image: apache/spark:3.5.3-python3
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  spark-worker:
    image: apache/spark:3.5.3-python3
    container_name: spark-worker
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
    ports:
      - "8081:8081"
    networks:
      - spark-net
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 2G
        reservations:
          cpus: '1.00'
          memory: 1G

  client:
    image: apache/spark:3.5.3-python3
    container_name: spark-client
    depends_on:
      - spark-master
      - spark-worker
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - spark-net
    environment:
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - PYTHONPATH=/app:/tmp/pip_packages/lib/python3.8/site-packages
      - KAGGLE_CONFIG_DIR=/tmp/kaggle_home
      - HOME=/tmp
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G

networks:
  spark-net:
    driver: bridge
